from __future__ import annotations

from .models import MethodSpec, ParameterSpec


def number(
    key: str,
    label: str,
    default: float,
    minimum: float,
    maximum: float,
    *,
    decimals: int = 3,
    suffix: str = "",
    help_text: str = "",
) -> ParameterSpec:
    return ParameterSpec(key, label, "float", default, minimum, maximum, decimals, suffix, help_text=help_text)


def integer(
    key: str,
    label: str,
    default: int,
    minimum: int,
    maximum: int,
    *,
    help_text: str = "",
) -> ParameterSpec:
    return ParameterSpec(key, label, "int", default, minimum, maximum, help_text=help_text)


def toggle(key: str, label: str, default: bool, help_text: str = "") -> ParameterSpec:
    return ParameterSpec(key, label, "bool", default, help_text=help_text)


def choice(
    key: str,
    label: str,
    default: str,
    options: tuple[tuple[str, str], ...],
    *,
    help_text: str = "",
) -> ParameterSpec:
    return ParameterSpec(key, label, "choice", default, choices=options, help_text=help_text)


def text(
    key: str,
    label: str,
    default: str = "",
    *,
    help_text: str = "",
) -> ParameterSpec:
    return ParameterSpec(key, label, "text", default, help_text=help_text)


INTEGRATION = choice(
    "integration",
    "Integración numérica",
    "simpson",
    (("Simpson acumulativa", "simpson"), ("Trapecios", "trapezoid")),
)

BUTTERWORTH = choice(
    "filter_family",
    "Familia de filtro",
    "butterworth",
    (("Butterworth (tesis)", "butterworth"),),
    help_text="Los scripts MATLAB de la tesis utilizan filtros Butterworth.",
)

FILTER_PHASE = choice(
    "filter_phase",
    "Aplicación del filtro",
    "zero_phase",
    (("Sin desfase · filtfilt (tesis)", "zero_phase"), ("Causal · una pasada", "causal")),
    help_text="El preajuste reproduce filtfilt, tal como aparece en los scripts de la tesis.",
)


METHOD_SPECS: tuple[MethodSpec, ...] = (
    MethodSpec(
        "trifunac_lee",
        "TL",
        "Trifunac y Lee",
        1990,
        "Filtra aceleración, velocidad y desplazamiento para controlar el ruido de alta frecuencia y la deriva de periodo largo.",
        "Registros cuyo desplazamiento final esperado es aproximadamente cero.",
        "El filtrado pasa alta elimina desplazamientos permanentes o cuasiestáticos.",
        "M. D. Trifunac y V. Lee, Automatic digitization and processing of accelerograms using PC, Report 90-3, USC, 1990.",
        "https://ri.uaemex.mx/bitstream/handle/20.500.11799/57875/TESIS_DAMARIS_ARIAS_final.pdf?sequence=1",
        "Apéndice B, pp. 43-57",
        59,
        "43",
        ("Aceleración", "Pasa baja", "Pasa alta", "Integrar a velocidad", "Pasa alta", "Integrar a desplazamiento", "Pasa alta"),
        (
            BUTTERWORTH,
            FILTER_PHASE,
            number("lowpass_hz", "Corte pasa baja", 25.0, 0.01, 500.0, suffix=" Hz"),
            integer("lowpass_order", "Orden pasa baja", 1, 1, 12, help_text="nroll_low = 1 en el script MATLAB."),
            number("highpass_hz", "Corte pasa alta", 0.07, 0.001, 100.0, suffix=" Hz"),
            integer("highpass_order", "Orden pasa alta", 1, 1, 12, help_text="nroll_high = 1 en el script MATLAB."),
            INTEGRATION,
        ),
        "#008BAC",
    ),
    MethodSpec(
        "chiu",
        "CH",
        "Chiu",
        1997,
        "Corrige una tendencia lineal en aceleración, filtra las bajas frecuencias y remueve la deriva integrada en velocidad o desplazamiento.",
        "Registros digitales de movimiento fuerte con desplazamiento final cercano a cero.",
        "La estimación depende sensiblemente del corte pasa alta; la variante elegida cambia el residual final.",
        "H.-C. Chiu, Stable baseline correction of digital strong-motion data, BSSA 87(4), 932-944, 1997.",
        "https://pubs.geoscienceworld.org/ssa/bssa/article/87/4/932/102643/Stable-Baseline-Correction-of-Digital-Strong-Motion",
        "Apéndice C, pp. 58-70",
        74,
        "58",
        ("Aceleración", "Ajuste lineal", "Pasa alta", "Pasa baja opcional", "Integrar", "Corregir deriva", "Integrar"),
        (
            BUTTERWORTH,
            FILTER_PHASE,
            integer("acceleration_degree", "Grado ajuste aceleración", 1, 0, 3),
            choice(
                "highpass_design",
                "Diseño pasa alta",
                "specifications",
                (("Especificaciones buttord (tesis)", "specifications"), ("Orden y corte manual", "manual")),
            ),
            number("passband_hz", "Esquina pasabanda Wp", 0.25, 0.001, 100.0, suffix=" Hz"),
            number("stopband_hz", "Esquina de rechazo Ws", 0.017, 0.0001, 100.0, decimals=4, suffix=" Hz"),
            number("passband_ripple_db", "Rizado pasabanda Rp", 0.5, 0.01, 20.0, decimals=2, suffix=" dB"),
            number("stopband_attenuation_db", "Atenuación rechazo Rs", 55.0, 1.0, 200.0, decimals=1, suffix=" dB"),
            number("highpass_hz", "Corte PA manual", 0.20, 0.001, 100.0, suffix=" Hz"),
            integer("highpass_order", "Orden PA manual", 4, 1, 12),
            toggle("use_lowpass", "Aplicar pasa baja", True),
            number("lowpass_hz", "Corte pasa baja", 30.0, 0.01, 500.0, suffix=" Hz"),
            integer("lowpass_order", "Orden pasa baja", 2, 1, 12, help_text="orden_low = 2 en el script MATLAB."),
            choice(
                "drift_correction",
                "Corrección final",
                "velocity",
                (("Ajuste en velocidad", "velocity"), ("Ajuste en desplazamiento", "displacement")),
            ),
            integer("final_degree", "Grado corrección final", 1, 0, 3),
            INTEGRATION,
        ),
        "#3CBFAE",
    ),
    MethodSpec(
        "converse_brady",
        "CB",
        "Converse y Brady",
        1992,
        "Implementa el flujo BAP: corrección de línea base, pads de ceros, filtrado pasa baja y pasa alta, y doble integración.",
        "Procesamiento reproducible de acelerogramas con banda útil conocida.",
        "Fuerza el residual hacia cero y los pads largos pueden dominar el costo de memoria.",
        "A. Converse y A. G. Brady, BAP Basic Strong-Motion Accelerogram Processing Software, USGS OFR 92-296-A, 1992.",
        "https://doi.org/10.3133/ofr92296A",
        "Apéndice D, pp. 71-82",
        87,
        "71",
        ("Aceleración", "Corregir línea base", "Pad inicial", "Pasa baja", "Completar pad", "Pasa alta", "Doble integración"),
        (
            BUTTERWORTH,
            FILTER_PHASE,
            choice("baseline", "Corrección de línea base", "linear", (("Recta grado 1 (tesis)", "linear"), ("Media", "mean"), ("Constante", "constant"))),
            number("baseline_constant", "Constante", 0.0, -100.0, 100.0, decimals=6, suffix=" m/s²"),
            number("lowpass_hz", "Corte pasa baja", 25.0, 0.01, 500.0, suffix=" Hz"),
            integer("lowpass_order", "Orden pasa baja", 2, 1, 12, help_text="order_low = 2 en el script MATLAB."),
            choice(
                "highpass_design",
                "Diseño pasa alta",
                "specifications",
                (("Especificaciones buttord (tesis)", "specifications"), ("Orden y corte manual", "manual")),
            ),
            number("passband_hz", "Esquina pasabanda Wp", 0.20, 0.001, 100.0, suffix=" Hz"),
            number("stopband_hz", "Esquina de rechazo Ws", 0.0085, 0.0001, 100.0, decimals=4, suffix=" Hz"),
            number("passband_ripple_db", "Rizado pasabanda Rp", 0.5, 0.01, 20.0, decimals=2, suffix=" dB"),
            number("stopband_attenuation_db", "Atenuación rechazo Rs", 55.0, 1.0, 200.0, decimals=1, suffix=" dB"),
            number("highpass_hz", "Corte PA manual", 0.07, 0.001, 100.0, suffix=" Hz"),
            integer("highpass_order", "Orden PA manual", 4, 1, 12),
            number("initial_pad_s", "Pad inicial por extremo", 2.0, 0.0, 60.0, suffix=" s"),
            number("high_pad_factor", "Factor pad pasa alta", 1.5, 0.1, 10.0, decimals=2),
            INTEGRATION,
        ),
        "#005199",
    ),
    MethodSpec(
        "boore",
        "BO",
        "Boore, Stephens y Joyner",
        2002,
        "Sustrae la media preevento y la derivada de un ajuste polinómico restringido en velocidad antes de integrar nuevamente.",
        "Registros sísmicos donde interesa conservar y estudiar desplazamiento residual.",
        "El tiempo de arribo y el filtro opcional deben someterse a análisis de sensibilidad.",
        "D. M. Boore, C. D. Stephens y W. B. Joyner, Comments on baseline correction..., BSSA 92(4), 1543-1560, 2002.",
        "https://doi.org/10.1785/0120000926",
        "Apéndice E, pp. 83-95",
        99,
        "83",
        ("Aceleración", "Media preevento", "Integrar", "Ajuste restringido", "Derivar y sustraer", "Pasa alta opcional", "Doble integración"),
        (
            BUTTERWORTH,
            FILTER_PHASE,
            number("arrival_s", "Tiempo de primer arribo", 1.0, 0.001, 100000.0, suffix=" s", help_text="Entrada manual T1 en la tesis; 1 s es sólo un punto de partida y debe ajustarse a la señal."),
            integer("velocity_degree", "Grado ajuste velocidad", 2, 1, 4),
            toggle("use_highpass", "Aplicar pasa alta", False),
            number("highpass_hz", "Corte pasa alta", 0.07, 0.001, 100.0, suffix=" Hz"),
            integer("highpass_order", "Orden pasa alta", 4, 1, 12),
            INTEGRATION,
        ),
        "#8F489A",
    ),
    MethodSpec(
        "wang",
        "WA",
        "Wang et al.",
        2011,
        "Busca una corrección continua de velocidad que haga que el desplazamiento final se aproxime a una función escalón.",
        "Sismos con desplazamiento cosísmico no nulo y preevento identificable.",
        "Es iterativo, más costoso y sensible a los límites temporales y al nivel de ruido.",
        "R. Wang et al., An improved automatic scheme for empirical baseline correction..., BSSA 101(5), 2029-2044, 2011.",
        "https://doi.org/10.1785/0120110039",
        "Apéndice F, pp. 96-109",
        112,
        "96",
        ("Detectar arribo", "Corregir media", "Integrar", "Detectar tiempos", "Ajustar postevento", "Buscar corrección continua", "Integrar"),
        (
            number("pre_event_s", "Ventana de ruido preevento", 5.0, 0.01, 10000.0, suffix=" s", help_text="La tesis solicita este tiempo al usuario; 5 s es un punto de partida, no un valor universal."),
            choice(
                "noise_metric",
                "Estimador de ruido",
                "mean_abs",
                (("Media del valor absoluto (tesis)", "mean_abs"), ("Desviación estándar", "std")),
            ),
            number("noise_multiplier", "Factor sobre ruido", 1.03, 0.1, 20.0, decimals=2),
            number("energy_fraction", "Energía acumulada final", 0.90, 0.50, 0.999, decimals=3),
            integer("post_degree", "Grado ajuste postevento", 2, 2, 3),
            integer(
                "grid_points",
                "Divisiones temporales",
                100,
                4,
                200,
                help_text="La tesis usa incrementos temporales te/100; el preajuste conserva 100 divisiones.",
            ),
            choice(
                "step_search_mode",
                "Búsqueda de d_f",
                "analytic",
                (("Óptimo analítico sin límites", "analytic"), ("Rango manual de la tesis", "manual_range")),
                help_text="El script pide límites manuales sin proponer valores. El modo analítico minimiza el mismo error sin imponerlos.",
            ),
            number("step_min_m", "d_f mínimo", -1.0, -1000.0, 1000.0, decimals=5, suffix=" m"),
            number("step_max_m", "d_f máximo", 1.0, -1000.0, 1000.0, decimals=5, suffix=" m"),
            number(
                "step_increment_fraction",
                "Incremento del rango d_f",
                0.025,
                0.001,
                1.0,
                decimals=3,
                help_text="delta_d_f = (d_f_max - d_f_min) × 0.025 en el script MATLAB.",
            ),
            toggle("limit_post_event", "Limitar postevento a 4 duraciones", True),
            INTEGRATION,
        ),
        "#F5A114",
    ),
    MethodSpec(
        "darragh",
        "DA",
        "Darragh, Silva y Gregor",
        2004,
        "Ajusta la velocidad con una forma lineal, cuadrática o bilineal, deriva la tendencia y la retira de la aceleración.",
        "Procesamiento PEER orientado a preservar componentes permanentes de registros cercanos a falla.",
        "La selección de forma y punto de quiebre requiere criterio y análisis de sensibilidad.",
        "R. B. Darragh, W. J. Silva y N. Gregor, Strong motion record processing procedures for the PEER center, COSMOS, 2004.",
        "https://www.strongmotion.org/archive/publications/reports/CP-2005-02.pdf",
        "Apéndice G, pp. 110-121",
        126,
        "110",
        ("Aceleración", "Integrar", "Ajustar velocidad", "Elegir forma", "Derivar y sustraer", "Pasa baja", "Doble integración"),
        (
            BUTTERWORTH,
            FILTER_PHASE,
            choice("fit_type", "Forma funcional", "auto", (("Elegir menor error", "auto"), ("Lineal", "linear"), ("Cuadrática", "quadratic"), ("Bilineal continua", "bilinear"))),
            number("fit_start_s", "Inicio del ajuste", 0.0, 0.0, 100000.0, suffix=" s", help_text="El script ajusta el registro completo; 0 s reproduce ese comportamiento."),
            number("breakpoint_s", "Quiebre bilineal (0 = auto)", 0.0, 0.0, 100000.0, suffix=" s", help_text="La tesis solicita Z manualmente. Cero permite estimarlo por búsqueda."),
            toggle("use_lowpass", "Aplicar pasa baja", True),
            number("lowpass_hz", "Corte pasa baja", 25.0, 0.01, 500.0, suffix=" Hz"),
            integer("lowpass_order", "Orden pasa baja", 2, 1, 12),
            INTEGRATION,
        ),
        "#CA252C",
    ),
    MethodSpec(
        "park",
        "PA",
        "Park et al.",
        2005,
        "Sustrae la media de aceleración y luego la media de velocidad antes de la segunda integración.",
        "Vibración de puentes con condiciones iniciales controladas y residual esperado cercano a cero.",
        "Es un ajuste básico; no separa deriva instrumental de contenido físico de baja frecuencia.",
        "K.-T. Park et al., The determination of bridge displacement using measured acceleration, Engineering Structures 27, 371-378, 2005.",
        "https://doi.org/10.1016/j.engstruct.2004.10.013",
        "Apéndice H, pp. 122-130",
        138,
        "122",
        ("Aceleración", "Restar media", "Integrar", "Restar media de velocidad", "Integrar"),
        (INTEGRATION,),
        "#6588B1",
    ),
    MethodSpec(
        "bunce_bridge",
        "BU",
        "Bunce et al. · Puentes",
        2023,
        "Ensaya múltiples ventanas de aceleración sin filtrar, retira una tendencia lineal y elige la doble integración con hombros más estables.",
        "Desplazamiento transitorio de puentes o viaductos durante el paso de vehículos y trenes, con señal antes y después de la carga.",
        "Exige acelerómetros de muy bajo ruido, condiciones inicial y final descargadas y tiempos de entrada/salida confiables; pierde robustez en cargas cuasiestáticas largas.",
        "A. Bunce et al., A robust approach to calculating bridge displacements from unfiltered accelerations for highway and railway bridges, MSSP 200, 110554, 2023.",
        "https://doi.org/10.1016/j.ymssp.2023.110554",
        "Secciones 2, 4 y 5",
        5,
        "4",
        (
            "Definir paso de carga",
            "Generar ventanas",
            "Ajuste lineal",
            "Doble integración",
            "Descartar levantamiento",
            "Evaluar hombros",
            "Evaluar recuperaciones del tren",
            "Clasificar",
        ),
        (
            choice(
                "event_mode",
                "Límites del paso",
                "automatic",
                (("Detección por energía", "automatic"), ("Definidos por el analista", "manual")),
                help_text="El artículo identifica la entrada y salida del vehículo en la aceleración. La detección automática es una ayuda local, no parte del método publicado.",
            ),
            number("event_start_s", "Entrada del tren", 0.0, 0.0, 100000.0, decimals=4, suffix=" s"),
            number("event_end_s", "Salida del tren", 0.0, 0.0, 100000.0, decimals=4, suffix=" s"),
            number("search_zone_s", "Zona de búsqueda por extremo", 2.0, 0.01, 60.0, decimals=3, suffix=" s"),
            number("candidate_step_s", "Paso entre ventanas", 0.02, 0.0001, 10.0, decimals=4, suffix=" s", help_text="Usa el periodo de muestreo para búsqueda exhaustiva; valores mayores reducen el tiempo de proceso."),
            integer("max_candidates", "Máximo de ventanas", 10000, 25, 250000),
            choice(
                "deflection_direction",
                "Dirección de la flecha",
                "automatic",
                (
                    ("Automática por excursión dominante", "automatic"),
                    ("Negativa; levantamiento positivo", "negative"),
                    ("Positiva; levantamiento negativo", "positive"),
                ),
                help_text="Automática resuelve la polaridad de cada candidato y registra la usada; selecciona una dirección manual si la convención del sensor está documentada.",
            ),
            number("max_lift_mm", "Levantamiento admisible", 5.0, 0.0, 1000.0, decimals=3, suffix=" mm"),
            choice(
                "quality_mode",
                "Control de calidad",
                "shoulders",
                (("Tren: hombros y recuperaciones", "train"), ("Carga móvil: hombros", "shoulders")),
                help_text="El control por hombros sólo requiere la señal. El control de tren añade las recuperaciones interiores P_i entre valles de carga T_i.",
            ),
            choice(
                "train_peak_source",
                "Origen de recuperaciones previstas",
                "geometry",
                (("Geometría de puente y tren", "geometry"), ("Tiempos introducidos", "manual")),
                help_text="La geometría aplica P_i=(d_i/L)T; la opción manual recibe directamente los segundos desde la entrada.",
            ),
            number(
                "bridge_span_m",
                "Luz del puente B",
                0.0,
                0.0,
                10000.0,
                decimals=3,
                suffix=" m",
                help_text="Distancia entre los apoyos de entrada y salida del vano instrumentado.",
            ),
            number(
                "sensor_position_m",
                "Sensor desde apoyo de entrada",
                0.0,
                0.0,
                10000.0,
                decimals=3,
                suffix=" m",
                help_text="Posición longitudinal del acelerómetro medida desde el apoyo por el que entra el tren; en centro de vano vale B/2.",
            ),
            number(
                "train_length_m",
                "Longitud entre ejes extremos",
                0.0,
                0.0,
                100000.0,
                decimals=3,
                suffix=" m",
                help_text="Distancia longitudinal desde el primer eje delantero hasta el último eje trasero, no la longitud entre topes.",
            ),
            text(
                "peak_midpoint_distances_m",
                "Huecos: puntos medios m_i",
                "",
                help_text="Metros desde el primer eje, separados por coma. Cada m_i representa una recuperación P_i entre dos valles de carga; seis conjuntos suelen producir cinco m_i.",
            ),
            choice(
                "train_timing_basis",
                "Base temporal",
                "event_duration",
                (("Duración observada T (publicación)", "event_duration"), ("Velocidad aproximada", "speed")),
                help_text="La duración observada usa entrada y salida; la velocidad permite calcular cada tiempo como d_i/v.",
            ),
            number(
                "train_speed_kmh",
                "Velocidad aproximada",
                0.0,
                0.0,
                500.0,
                decimals=2,
                suffix=" km/h",
                help_text="Velocidad media durante el cruce. Sólo se usa cuando la base temporal seleccionada es velocidad.",
            ),
            text(
                "expected_peak_offsets_s",
                "Recuperaciones P_i desde entrada",
                "",
                help_text="Tiempos positivos y crecientes, en segundos. Son recuperaciones entre valles de carga, no los máximos de flecha producidos por cada conjunto de ejes.",
            ),
            number(
                "peak_tolerance_s",
                "Tolerancia P_i vs. recuperación",
                0.35,
                0.001,
                10.0,
                decimals=3,
                suffix=" s",
                help_text="Diferencia temporal máxima para asociar de forma única una recuperación detectada con cada P_i previsto.",
            ),
            number(
                "minimum_peak_spacing_s",
                "Separación mínima de recuperaciones",
                1.5,
                0.001,
                120.0,
                decimals=3,
                suffix=" s",
                help_text="MinPeakDistance equivalente. Bunce et al. usaron 1.5 s para sus trenes; debe adaptarse a la geometría y velocidad del caso analizado.",
            ),
            number(
                "minimum_peak_width_s",
                "Anchura mínima de recuperación",
                1.5,
                0.001,
                120.0,
                decimals=3,
                suffix=" s",
                help_text="MinPeakWidth equivalente. El valor de 1.5 s corresponde al caso ferroviario publicado, no es universal.",
            ),
            number(
                "minimum_peak_prominence_mm",
                "Prominencia mínima de recuperación",
                1.0,
                0.0,
                1000.0,
                decimals=3,
                suffix=" mm",
                help_text="MinPeakProminence equivalente. La publicación usó 1 mm para excluir oscilaciones pequeñas.",
            ),
            choice(
                "integration",
                "Integración numérica",
                "trapezoid",
                (("Trapecios (referencia)", "trapezoid"), ("Simpson acumulativa", "simpson")),
            ),
        ),
        "#007F73",
        local_reference_file="references/bunce_bridge_displacement_2023.pdf",
        local_reference_page=5,
        reference_basis="publicación",
    ),
)


METHOD_BY_ID = {spec.method_id: spec for spec in METHOD_SPECS}
